### ISSUE TITLE
File upload limited to 100MB

### ISSUE THREAD

**Issue by RabidAnubis** [paladini/voice-separator-demucs#2]
Hi! Many thanks for this great project.

 In my use cxase I'm taking wav files out of a Digital Audio Workstation (DAW), Ardour and using demucs to remove background instruments from vocal tracks. However often because of multiple takes of a song or recoding multiple songs in studio the wav files are larger than 100MB.

Is there a way I can up the limit? Is there a way to remove the limit?

Many thanks!

**Comment by paladini** [comment]
> Hi! Many thanks for this great project.
> 
> In my use case I'm taking wav files out of a Digital Audio Workstation (DAW), Ardour and using demucs to remove background instruments from vocal tracks. However often because of multiple takes of a song, or recoding multiple songs in studio, the wav files are larger than 100MB.
> 
> Is there a way I can up the limit? Is there a way to remove the limit?
> 
> Many thanks!

It's really great to hear that this project is already proving useful to someone — thanks for the kind words!

And thank you for providing the additional context; that really helps clarify what you're trying to achieve. You're absolutely right — having no limit at all would make a lot of sense in your use case. The limit was originally put in place because I was planning to host this as a free online service. However, I ran into a few challenges and ended up shifting the focus toward a self-hosted desktop application instead.

That said, I'm happy to remove the limit for you! I’ll take a look and make the necessary changes as soon as possible. It might take me up to a week to publish an updated Docker image, but I’ll keep you posted.

@RabidAnubis, just to confirm — how are you currently running the application? Are you using the Docker container, or are you running it directly from the source?

**Comment by paladini** [comment]
Hey @RabidAnubis , how are you?

I've implemented the code to meet your request ( https://github.com/paladini/voice-separator-demucs/pull/3 ), but I still need to build and publish a new Docker image version. I'll let you know as soon as it's available. Thanks again for your patience and for contributing to the project with your suggestions!

**Comment by paladini** [comment]
Hi, @RabidAnubis . I have pushed a new image to Docker Hub. If you're using Latest version, you should not do anything besides download the image again. 

Anyway, I have released version 1.1 as well. 
Can you take a look if this solves your problem?

[https://hub.docker.com/repository/docker/paladini/voice-separator/general](https://hub.docker.com/repository/docker/paladini/voice-separator/general)

**Comment by RabidAnubis** [comment]
Hi @paladini I still get the error message. Screenshot attached.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/af725f03-d14d-4eb2-a9fd-ab7c30562602" />

**Comment by paladini** [comment]
Can you try again, @RabidAnubis ? I just have pushed a new version and replaced old "latest" version.

<img width="840" height="665" alt="Image" src="https://github.com/user-attachments/assets/ef3dca6e-04e5-445d-b181-fc0b16a46a0d" />

**Comment by RabidAnubis** [comment]
Thanks! I got past the size limit error now it complains that the wav file should be stereo. In my case it's mono.

<img width="619" height="276" alt="Image" src="https://github.com/user-attachments/assets/b62d2a11-bbfb-4858-aab7-1cd7453a57a9" />

**Comment by paladini** [comment]
> Thanks! I got past the size limit error now it complains that the wav file should be stereo. In my case it's mono.
> 
> <img alt="Image" width="619" height="276" src="https://private-user-images.githubusercontent.com/6379024/475126995-b62d2a11-bbfb-4858-aab7-1cd7453a57a9.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTUyMjMyMzMsIm5iZiI6MTc1NTIyMjkzMywicGF0aCI6Ii82Mzc5MDI0LzQ3NTEyNjk5NS1iNjJkMmExMS1iYmZiLTQ4NTgtYWFiNy0xY2Q3NDUzYTU3YTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDgxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA4MTVUMDE1NTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGQ3MjkwMTZjZGNmNDJhMWNhMDc2YzIzNTE2NWM1Njg0NGU2ODRiYTdlNTI4MzUzODc4ODc3NTE0ODk2ZmQ1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.rfcmABgwL_Tq6J8yZjUayitu--oiITDrT8A42Ur_qqA">

@RabidAnubis Hi there! Thanks so much for the detailed feedback. I'm happy to know that the file size problem is now resolved.

As for the new error message about the WAV file needing to be stereo, let's look into that. To help us track this new issue more efficiently, would you mind opening a new issue on the repository?

It would be a huge help if you could share the .wav file that's causing the error. This will allow me to reproduce and debug the problem on my end.

I really appreciate you testing this and for your ongoing contribution.

**Comment by RabidAnubis** [comment]
Any mono 48KHz wav file will be fine for testing. I can make one for you if you wish. The one I used in the above example is huge (>1GB).
